[roll third_party/pigweed] pw_build: Fix Python Tree Tests
There was a problem with this test if the setuptools-scm package was
installed inside the Pigweed virtualenv. An exception gets raised if
the fake pyproject.toml does not have a valid syntax:

  tomli.TOMLDecodeError: Expected "=" after a key in a key/value pair

The exception doesn't occur if setuptools-scm is not installed. It
can't hurt to use valid file contents for these tests so this change
does that.

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/80222

https://pigweed.googlesource.com/pigweed/pigweed
third_party/pigweed Rolled-Commits: f6522afd39b8a19..6d1555ddaa5bd6d
Roller-URL: https://ci.chromium.org/b/8824477740937810705
Cq-Cl-Tag: roller-builder:pigweed-sample-project-roller
Cq-Cl-Tag: roller-bid:8824477740937810705
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I6d44d2ed3437368cd909da151c4ab930f3fefd6e
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/sample_project/+/80561
Bot-Commit: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>