[roll third_party/pigweed] pw_protobuf: Add restrict version in setup.cfg
pw_protobuf's setup.cfg previously restricted protobuf>=3.20.1, often
leading to newer much newer protobuf versions getting installed (e.g.
4.x).

Unfortunately, CIPD is currently shipping protoc 3.17.3, which is not
directly compatible with those newer protobuf versions. This commit
adds a restriction that protobuf<=3.20.3, the last protobuf version
compatible with protoc 3.17.3.

Once protoc is upgraded in CIPD this restriction may be able to be
lifted.

Error Message:
==============================
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of
date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible
workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use
    pure-Python parsing and will be much slower).

More information:
https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

==============================

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/141370

https://pigweed.googlesource.com/pigweed/pigweed
third_party/pigweed Rolled-Commits: 69eab47bac1bda7..fcee66299ef054e
Roller-URL: https://ci.chromium.org/b/8781541135849753025
GitWatcher: ignore
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I6bded321b58d773c5cf7a6c9254d5cbb83d607e2
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/sample_project/+/146194
Bot-Commit: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>