[roll third_party/pigweed] pw_docgen: sphinxcontrib-mermaid workaround:
Version >=4.0.0 of Sphinx removes some APIs, one of which is used by
sphinxcontrib-mermaid. Error:

Running Sphinx v4.0.0
Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name
'ENOENT' from 'sphinx.util.osutil'

Failed roll:
https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/44223

This workaround can be removed after
https://github.com/mgaitan/sphinxcontrib-mermaid/pull/71 is merged.

No-Docs-Update-Reason: Sphinx 4.0 workaround.
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/44320

third_party/pigweed Rolled-Commits: 778529737faa78c..56f4a2cdc97d341
Roller-URL: https://ci.chromium.org/b/8847587026915824176
Cq-Cl-Tag: roller-builder:pigweed-sample-project-roller
Cq-Cl-Tag: roller-bid:8847587026915824176
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I3040f2bc9e2d458f9d086d1040e4f175d0f4582a
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/sample_project/+/44380
Reviewed-by: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>