[roll third_party/pigweed] pw_console: Missing default_factory for dataclasses
Fixes the Python 3.11 error:
ValueError: mutable default <class 'collections.deque'> for field
history is not allowed: use default_factory.

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/135481

https://pigweed.googlesource.com/pigweed/pigweed
third_party/pigweed Rolled-Commits: f4dd9366fb797dd..7e67d0fb4d1e033
Roller-URL: https://ci.chromium.org/b/8785728082123532145
GitWatcher: ignore
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I8e494e1d14f857b346d2afcaed5f56a1a0b045d1
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/sample_project/+/135550
Bot-Commit: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>